### ISSUE TITLE
support cmdliner 1.0 interface

### ISSUE THREAD

**Issue by avsm** [moby/datakit#496] opened 2017-03-13 10:41 UTC
The `Cmdliner.Arg.conv` is now abstract, so it fails with this on Cmdliner 1.0:

```
# File "src/datakit_log.ml", line 66, characters 19-23:
# Error: This expression has type
#          ?docv:string ->
#          (string -> ('a, [ `Msg of string ]) Result.result) *
#          'a Cmdliner.Arg.printer -> 'a Cmdliner.Arg.conv
#        but an expression was expected of type
#          'b Cmdliner.Arg.conv =
#            'b Cmdliner.Arg.parser * 'b Cmdliner.Arg.printer
# Command exited with code 2.
```

**Comment by dbuenzli** [comment] 2017-03-13 14:51
> The Cmdliner.Arg.conv is now abstract, so it fails with this on Cmdliner 1.0

No it's not. The problem is that the `Arg.conv` value was added to the `Arg` module so the [`conv`](https://github.com/docker/datakit/blob/master/src/datakit_log.ml#L66) on that line is not the one [up there](https://github.com/docker/datakit/blob/master/src/datakit_log.ml#L9) that is supposed to be, but the one from the module.

**Comment by talex5** [comment] 2017-04-28 08:52
Fixed by https://github.com/moby/datakit/pull/531.

**Closed by talex5** 2017-04-28 08:52 UTC
Labels: kind/upgrade-treadmill
